name: release-build-linux

on:
  push:
    branches:
    - master
  pull_request:

  release:
    types: [created] 

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v2
    - name: Install graalvm
      uses: DeLaGuardo/setup-graalvm@3
      with:
        graalvm-version: '20.0.0.java11'
    - name: Install native-image
      run: gu install native-image
    - name: Set version
      run: ./mvnw versions:set -DnewVersion="${{ github.run_number }}" 
    - name: Build native executable
      run: ./mvnw package -Dnative 
    - name: Upload native executable
      id: upload-native-executable
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event_path }}/${{ github.run_number }}
        asset_path: ./target/starfish-${{ github.run_number }}-runner
        asset_name: starfish-native-linux
        asset_label: linux
        asset_content_type: application/octet-stream
